/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as LawyersRouteImport } from './routes/lawyers'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SummarizerRouteImport } from './routes/summarizer'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RightsIndexRouteImport } from './routes/rights/index'
import { Route as RightsSlugRouteImport } from './routes/rights/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersRoute = LawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsIndexRoute = RightsIndexRouteImport.update({
  id: '/rights/',
  path: '/rights/',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsSlugRoute = RightsSlugRouteImport.update({
  id: '/rights/$slug',
  path: '/rights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/helpline': typeof HelplineRoute
  '/lawyers': typeof LawyersRoute
  '/news': typeof NewsRoute
  '/summarizer': typeof SummarizerRoute
  '/templates': typeof TemplatesRoute
  '/rights/$slug': typeof RightsSlugRoute
  '/rights/': typeof RightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/helpline': typeof HelplineRoute
  '/lawyers': typeof LawyersRoute
  '/news': typeof NewsRoute
  '/summarizer': typeof SummarizerRoute
  '/templates': typeof TemplatesRoute
  '/rights/$slug': typeof RightsSlugRoute
  '/rights': typeof RightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/helpline': typeof HelplineRoute
  '/lawyers': typeof LawyersRoute
  '/news': typeof NewsRoute
  '/summarizer': typeof SummarizerRoute
  '/templates': typeof TemplatesRoute
  '/rights/$slug': typeof RightsSlugRoute
  '/rights/': typeof RightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/glossary'
    | '/helpline'
    | '/lawyers'
    | '/news'
    | '/summarizer'
    | '/templates'
    | '/rights/$slug'
    | '/rights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/glossary'
    | '/helpline'
    | '/lawyers'
    | '/news'
    | '/summarizer'
    | '/templates'
    | '/rights/$slug'
    | '/rights'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/glossary'
    | '/helpline'
    | '/lawyers'
    | '/news'
    | '/summarizer'
    | '/templates'
    | '/rights/$slug'
    | '/rights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  GlossaryRoute: typeof GlossaryRoute
  HelplineRoute: typeof HelplineRoute
  LawyersRoute: typeof LawyersRoute
  NewsRoute: typeof NewsRoute
  SummarizerRoute: typeof SummarizerRoute
  TemplatesRoute: typeof TemplatesRoute
  RightsSlugRoute: typeof RightsSlugRoute
  RightsIndexRoute: typeof RightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers': {
      id: '/lawyers'
      path: '/lawyers'
      fullPath: '/lawyers'
      preLoaderRoute: typeof LawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights/': {
      id: '/rights/'
      path: '/rights'
      fullPath: '/rights/'
      preLoaderRoute: typeof RightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights/$slug': {
      id: '/rights/$slug'
      path: '/rights/$slug'
      fullPath: '/rights/$slug'
      preLoaderRoute: typeof RightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  GlossaryRoute: GlossaryRoute,
  HelplineRoute: HelplineRoute,
  LawyersRoute: LawyersRoute,
  NewsRoute: NewsRoute,
  SummarizerRoute: SummarizerRoute,
  TemplatesRoute: TemplatesRoute,
  RightsSlugRoute: RightsSlugRoute,
  RightsIndexRoute: RightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
